from __future__ import annotations

from workflow_policy_contract import PHASE_READ_POLICY
from workflow_stage_roles import GRAPH_STAGE_ROLES


TOP_LEVEL_RESIDENT_DOCS = PHASE_READ_POLICY["top_level_resident_docs"]

STAGES = {
    "mother_doc": {
        "objective": "Write the live requirement into the existing protocol-driven mother doc system instead of expanding a giant mixed tree. This stage starts from resident norms, indexes, overview branches, the current mother_doc state, the latest archived iteration, and current code reality; it then places the current topic into the right layer of the doc system, keeps the narrative descending from human-facing framing to machine-facing contracts, and synchronizes affected overview/index docs when the global shape changes. Structural governance stays subordinate: use mother-doc-audit only when overload, ambiguity, drift, or a major rewrite makes it useful, and never auto-select the next deeper anchor topic without explicit user direction.",
        "required_outputs": [
            "<docs_root>/mother_doc/ directory",
            "<target_root>/Client_Applications/mother_doc mirror refreshed from <docs_root>/mother_doc",
            "00_index.md auto-generated root folder graph",
            "protocol-governed atomic docs with status, viewer, and anchor frontmatter",
            "mother doc content aligned to the live requirement source instead of audit-first tree repair",
            "resident overview/index/common-rule docs kept in sync when topic-level changes alter the global shape",
        ],
        "resident_docs": TOP_LEVEL_RESIDENT_DOCS,
        "stage_docs": [
            "<docs_root>/mother_doc/00_index.md",
            "<docs_root>/mother_doc/*",
            "<docs_root>/<latest_NN_slug>/* when present",
            "Skills/Workflow-MotherDoc-OctopusOS/path/stage_flow/*",
            "Skills/Workflow-MotherDoc-OctopusOS/assets/mother_doc/*",
            "Skills/Workflow-MotherDoc-OctopusOS/assets/agents/*",
            "Skills/Workflow-MotherDoc-OctopusOS/assets/REQUIREMENT_ATOM_TEMPLATE.md",
            "Skills/Workflow-MotherDoc-OctopusOS/assets/mother_doc_audit/* when structural governance is explicitly invoked",
            "Meta-code-graph-base context/resource when available",
        ],
        "graph_role": GRAPH_STAGE_ROLES["mother_doc"],
        "stage_entry_actions": [
            "run target-runtime-contract before reading or writing stage artifacts",
            "confirm docs_root through Dev-ProjectStructure-Constitution when the project has already fixed a custom development-doc container",
            "if <docs_root>/mother_doc is missing, run target-scaffold",
            "start from the live request, project AGENTS, resident overview/index/common-rule docs, the current mother_doc tree, and the latest archived iteration before invoking any governance-only helper",
            "run Meta-Impact-Investigation in WRITE_INTENT mode before deciding any mother_doc write scope",
            "if execution packs already exist, inspect them as current task lineage rather than inventing a disconnected second planning context",
            "if the repo already has substantive code, check Meta-code-graph-base runtime first and initialize it when missing",
            "read <docs_root>/mother_doc/00_index.md and then deepen only along the branches needed by the current semantic move",
            "treat top-level overview/index/common-rule docs as resident structure, not as dumping grounds for implementation semantics",
            "extract reusable target state, stable architecture decisions, blockers, and unfinished delivery deltas from the latest archive when present",
            "read graph context only after the requirement-source intake so code reality can correct stale assumptions without replacing intent",
            "decide whether this round should edit current nodes, rewrite nodes, migrate nodes, delete nodes, extend vertically, or branch horizontally",
            "when a new deeper anchor doc would be needed, require the user to name that next topic explicitly before creating the new anchor node",
            "invoke mother-doc-audit only when the current tree is overloaded, ambiguous, drifting, or about to receive a substantial structural rewrite",
            "before creating a new vertical layer or horizontal branch family, register it in the skill and confirm it is reusable for sibling semantics",
            "before any real write, reduce the current change into the smallest mother_doc slice that can still close the intended semantic move",
            "after topic-level writeback changes the global architecture shape, sync the related overview, common-rule, and entry-map docs in the same turn",
            "after any mother_doc structural write, run mother-doc-refresh-root-index so 00_index.md is regenerated from folders only",
            "after the root index refresh, run mother-doc-sync-client-copy so the Client_Applications viewer mirror is force-overwritten from the Development_Docs source tree",
            "run mother-doc-lint before leaving the stage",
            "rerun mother-doc-audit only when this round materially changed folder structure or when governance debt is still suspected after writeback",
        ],
        "stage_exit_gate": [
            "mother-doc-lint passes",
            "current mother_doc reflects the live requirement source plus inherited stable decisions from the latest archive when such an archive exists",
            "<docs_root>/mother_doc remains the only write source of truth and the client mirror has been refreshed after this turn's mother_doc edits",
            "00_index.md exists as the fixed root placeholder and is refreshed from the current folder structure",
            "no replace_me remains",
            "atomic docs expose the minimal frontmatter + anchor protocol",
            "any newly created deeper anchor doc corresponds to a topic explicitly named by the user",
            "the current writeback keeps mother_doc as a layered documentation flow instead of turning it into a mixed frontend/backend/construction mega-branch",
            "if mother-doc-audit was explicitly invoked, any blocking debt it exposed has been resolved or deliberately written down as a follow-up instead of being silently carried forward",
            "any newly introduced vertical layer or horizontal branch family has been registered in the skill and is reusable beyond a single node",
        ],
        "optional_governance_actions": [
            "mother-doc-audit for overloaded or drifting trees",
            "registry-backed split or migration guidance when the tree can no longer carry the semantic move cleanly",
        ],
        "drop_on_stage_switch": [
            "mother_doc chapter drafting focus",
            "mother_doc template fill guidance",
            "stage-local governance triage notes that were not written back into the mother doc or follow-up docs",
        ],
    },
    "construction_plan": {
        "objective": "Read the completed protocol-driven mother doc tree, crawl the full document set, locate the current modified docs, understand their anchor-linked context, then generate an official Execution_atom_plan&validation_packs tree for implementation and stage acceptance. This stage decomposes work from the changed mother_doc slice; it must not re-decide the primary architecture that should already be settled in mother_doc.",
        "required_outputs": [
            "<docs_root>/mother_doc/execution_atom_plan_validation_packs/ directory",
            "00_index.md plus numbered pack directories",
            "per-pack markdown anchors and machine-writeable manifests/ledgers",
            "source_mother_doc_refs carried by each numbered pack",
            "pack decomposition decided from the current modified mother_doc slice rather than a fixed planning document path",
        ],
        "resident_docs": TOP_LEVEL_RESIDENT_DOCS,
        "stage_docs": [
            "<docs_root>/mother_doc/* with doc_work_state=modified|planned|ref as needed",
            "<docs_root>/mother_doc/execution_atom_plan_validation_packs/00_index.md",
            "<docs_root>/mother_doc/execution_atom_plan_validation_packs/*",
            "Skills/Workflow-ConstructionPlan-OctopusOS/path/stage_flow/*",
            "Skills/Workflow-ConstructionPlan-OctopusOS/assets/execution_atom_plan_validation_packs/*",
            "Meta-code-graph-base context/resource when available",
            "codebase files only after mother-doc-lint passes",
        ],
        "graph_role": GRAPH_STAGE_ROLES["construction_plan"],
        "stage_entry_actions": [
            "run target-runtime-contract before touching execution packs",
            "reload the construction_plan stage checklist before reading execution packs",
            "read graph context before pack decomposition when the codebase already exists",
            "scan the complete mother_doc tree instead of assuming a fixed planning document path",
            "use doc_work_state=modified as the seed set, then cluster those docs with their anchor-linked context into packs; do not batch-flip unrelated docs to planned",
            "classify any existing execution_atom_plan_validation_packs root before reuse: preview_skeleton must be replaced, accepted/retired plans must not be reused as fresh construction input",
            "only an official_plan with plan_state=planned_unused or in_execution and current pack coverage may remain as the current round plan root",
            "run target-scaffold only when the mother_doc root itself is missing; construction plan roots are initialized explicitly, not as a side effect of mother_doc scaffold",
            "run construction-plan-lint before leaving the stage",
        ],
        "stage_exit_gate": [
            "construction plan root is separate from mother doc design plan",
            "construction plan root is explicitly classified as official_plan or preview_skeleton",
            "each numbered pack directory contains its own markdown anchors and machine files",
            "each numbered pack declares source_mother_doc_refs for implementation readback",
            "each pack defines inner development phases, validation slices, evidence writeback, and stage acceptance",
            "official packs were derived from the current modified mother_doc slice rather than copied from a single planning doc",
        ],
        "drop_on_stage_switch": [
            "mother_doc drafting focus",
            "construction_plan pack decomposition focus once the next stage checklist is loaded",
        ],
    },
    "implementation": {
        "objective": "Implement strictly according to the active execution atom pack, read only the mother_doc atoms explicitly referenced by that pack, update its ledgers and evidence files pack-by-pack, and prove each test result matches design intent rather than only checking that a feature appears to work.",
        "required_outputs": [
            "code",
            "tests",
            "updated <docs_root>/mother_doc/execution_atom_plan_validation_packs/*",
            "linked mother_doc docs advanced from planned to developed when the active pack is implemented and locally validated",
            "ADR records when architecture decisions change",
        ],
        "resident_docs": TOP_LEVEL_RESIDENT_DOCS,
        "stage_docs": [
            "<docs_root>/mother_doc/execution_atom_plan_validation_packs/00_index.md",
            "<docs_root>/mother_doc/execution_atom_plan_validation_packs/<active_pack>/*",
            "<docs_root>/mother_doc/<source_mother_doc_refs declared by active_pack>",
            "<docs_root>/mother_doc/<ref docs when explicitly needed>",
            "Skills/Workflow-Implementation-OctopusOS/path/stage_flow/*",
            "concrete codebase files needed by the active pack and inner phase",
        ],
        "graph_role": GRAPH_STAGE_ROLES["implementation"],
        "stage_entry_actions": [
            "run target-runtime-contract before reading the active pack so implementation stays attached to the current task lineage",
            "reload the implementation checklist and discard construction_plan decomposition notes that are not part of the active pack",
            "do_not_pull_graph_context_into_implementation_focus; read concrete code and tests directly",
            "read only an execution-eligible official active pack plus the source_mother_doc_refs declared by that pack; do not sweep unrelated modified docs into implementation focus",
            "preview_skeleton or accepted/retired plan roots must be rejected before implementation starts",
            "run phase validation before moving to the next inner phase or pack",
        ],
        "stage_exit_gate": [
            "current pack and inner phase code/tests are on disk",
            "phase_status.jsonl and evidence_registry.json reflect sequencing changes and evidence refs",
            "relevant tests have already been run before moving to the next inner phase or pack",
            "linked mother_doc docs can advance from planned to developed only after local implementation plus validation complete",
            "the active pack explains why the changed result and tests satisfy design intent and stage acceptance",
        ],
        "drop_on_stage_switch": [
            "completed pack execution focus after acceptance starts",
            "implementation-only local debugging notes not required by acceptance evidence",
        ],
    },
    "acceptance": {
        "objective": "Bring the locally controllable runtime all the way to production-like readiness, then decide delivery against the mother doc and real witness evidence. Acceptance must finish local configuration, secrets resolution, resident services, health checks, simulated human interaction, evidence writeback, and graph postflight before mother_doc docs advance into ref state; if the run is closed, archive mother_doc into the next numbered docs directory during evidence closeout.",
        "required_outputs": ["acceptance report", "acceptance matrix"],
        "resident_docs": TOP_LEVEL_RESIDENT_DOCS,
        "stage_docs": [
            "<docs_root>/mother_doc/* with doc_work_state=developed|ref as needed",
            "<docs_root>/mother_doc/execution_atom_plan_validation_packs/<active_or_completed_pack>/*",
            "<docs_root>/mother_doc/acceptance/*",
            "Skills/Workflow-Acceptance-OctopusOS/path/stage_flow/*",
            "Skills/Workflow-Acceptance-OctopusOS/assets/acceptance/*",
            "test outputs and live witness evidence",
        ],
        "graph_role": GRAPH_STAGE_ROLES["acceptance"],
        "stage_entry_actions": [
            "run target-runtime-contract before reading acceptance artifacts so delivery remains attached to the current task lineage",
            "reload the acceptance checklist before reading acceptance artifacts",
            "discard implementation-only editing focus and keep only evidence needed for delivery judgement",
            "finish all locally controllable environment bring-up work before allowing needs_real_env",
            "resolve project-declared local secrets, credentials, and runtime endpoints from ignored env files or other non-git secret sources declared in 07_env_and_deploy.md and project AGENTS",
            "start and verify the project-declared resident runtime surfaces until health, dependency connectivity, and observable runtime signals are available",
            "run at least one simulated human or operator path through the real local stack and capture logs, files, service traces, UI witness, or delivery refs as the project requires",
            "run acceptance-lint before final closure",
        ],
        "stage_exit_gate": [
            "acceptance-lint passes",
            "requirement-level evidence is linked",
            "all locally controllable configuration is applied and documented, including env files, credentials, startup settings, and runtime endpoints declared by the project",
            "local runtime surfaces are running and have passed health and connectivity checks required by the project",
            "at least one simulated usage flow has traversed the intended runtime path and produced real witness refs",
            "blocked states are explicit where witness is still unavailable",
            "graph-postflight is triggered during closeout after acceptance evidence is complete",
            "linked mother_doc docs advance from developed to ref only after acceptance evidence and graph postflight are complete",
            "optional closeout archive happens only after evidence is complete",
        ],
        "drop_on_stage_switch": [
            "implementation editing focus",
            "unfinished stage-local hypotheses that are not backed by acceptance evidence",
        ],
    },
}
