from __future__ import annotations

# contract_name: octopus_devflow_workflow_contract_data
# contract_version: 2.1.0
# validation_mode: strict
# required_fields:
#   - STAGES
#   - TEMPLATES
#   - REQUIREMENT_ATOM_FIELDS
#   - BASELINE_MODES
#   - BLOCKED_STATES
#   - DESIGN_PHASE_PLAN_SECTIONS
#   - EXECUTION_ATOM_PACK_ROOT_FILES
#   - EXECUTION_ATOM_PACK_MARKDOWN_FILES
#   - EXECUTION_ATOM_PACK_MACHINE_FILES
#   - EXECUTION_ATOM_PHASE_FIELDS
#   - ACCEPTANCE_FIELDS
#   - ACCEPTANCE_MATRIX_FIELDS
#   - ACCEPTANCE_LINT_POLICY
#   - ADR_REQUIRED_SECTIONS
#   - PHASE_READ_POLICY
# optional_fields: []

from workflow_policy_contract import (
    ACCEPTANCE_FIELDS,
    ACCEPTANCE_LINT_POLICY,
    ACCEPTANCE_MATRIX_FIELDS,
    ADR_REQUIRED_SECTIONS,
    BASELINE_MODES,
    BLOCKED_STATES,
    DESIGN_PHASE_PLAN_SECTIONS,
    DISCOVERY_SCOPE_POLICY,
    MOTHER_DOC_FRONTMATTER_FIELDS,
    MOTHER_DOC_GOVERNANCE_POLICY,
    MOTHER_DOC_WORK_STATES,
    EXECUTION_ATOM_PACK_MACHINE_FILES,
    EXECUTION_ATOM_PACK_MARKDOWN_FILES,
    EXECUTION_ATOM_PACK_ROOT_FILES,
    EXECUTION_ATOM_PHASE_FIELDS,
    IMPLEMENTATION_SOURCE_POLICY,
    PHASE_READ_POLICY,
    REQUIREMENT_ATOM_FIELDS,
)
from workflow_stage_contract import STAGES
from workflow_template_contract import TEMPLATES
